Repository MountainDash/nonebot-bison, pull requests merged in 2022-10, with the labels that each got.

#111 fix: 修复 bilibili-live 中获取状态错误后产生的错误行为
  src/plugins/nonebot_bison/platform/bilibili.py
Labels: bug

#110 feat: 临时解决 bilibili 的反爬机制
  src/plugins/nonebot_bison/platform/bilibili.py
  src/plugins/nonebot_bison/utils/http.py
  tests/platforms/test_bilibili_live.py
  tests/test_config_manager_add.py
Labels: feature

#115 处理「添加重复订阅」异常
  poetry.lock
  src/plugins/nonebot_bison/admin_page/api.py
  src/plugins/nonebot_bison/config/db_config.py
  src/plugins/nonebot_bison/config_manager.py
  tests/config/test_config_operation.py
  tests/test_custom_post.py
Labels: bug

#118 修复前端面包屑错误
  admin-frontend/src/pages/Home.tsx
Labels: bug

#119 修复添加按钮没反应
  admin-frontend/src/features/subsribeConfigManager/GroupManager.tsx
Labels: bug

#120 使用新的文件来标志 legacy db 已弃用
  src/plugins/nonebot_bison/config/config_legacy.py
  tests/conftest.py
Labels: bug

#121 修复前端 title
  admin-frontend/public/index.html
Labels: bug

#127 update workflow
  .github/workflows/main.yml
Labels: skip-changelog

#126 由 scheduler 提供 http client
  src/plugins/nonebot_bison/admin_page/api.py
  src/plugins/nonebot_bison/apis.py
  src/plugins/nonebot_bison/config_manager.py
  src/plugins/nonebot_bison/platform/__init__.py
  src/plugins/nonebot_bison/platform/arknights.py
  src/plugins/nonebot_bison/platform/bilibili.py
  src/plugins/nonebot_bison/platform/ff14.py
  src/plugins/nonebot_bison/platform/mcbbsnews.py
  src/plugins/nonebot_bison/platform/ncm.py
  src/plugins/nonebot_bison/platform/ncm_artist.py
  src/plugins/nonebot_bison/platform/ncm_radio.py
  src/plugins/nonebot_bison/platform/platform.py
  src/plugins/nonebot_bison/platform/rss.py
  src/plugins/nonebot_bison/platform/weibo.py
  src/plugins/nonebot_bison/scheduler/scheduler.py
  src/plugins/nonebot_bison/utils/scheduler_config.py
  tests/platforms/test_arknights.py
  tests/platforms/test_bilibili.py
  tests/platforms/test_bilibili_bangumi.py
  tests/platforms/test_bilibili_live.py
  tests/platforms/test_ff14.py
  tests/platforms/test_mcbbsnews.py
  tests/platforms/test_ncm_artist.py
  tests/platforms/test_ncm_radio.py
  tests/platforms/test_platform.py
  tests/platforms/test_platform_tag_filter.py
  tests/platforms/test_weibo.py
  tests/test_config_manager_abort.py
  tests/test_config_manager_add.py
  tests/test_render.py
Labels: feature

#108 优化文档描述
  docs/dev/README.md
  docs/usage/README.md
Labels: documentation, skip-changelog

#129 fix platform store init error
  src/plugins/nonebot_bison/platform/platform.py
  tests/platforms/test_platform.py
Labels: bug, skip-changelog

#124 前端适配移动端设备
  admin-frontend/src/features/subsribeConfigManager/GroupManager.tsx
  admin-frontend/src/features/subsribeConfigManager/SubscribeManager.tsx
  admin-frontend/src/features/subsribeConfigManager/SubscribeModal.tsx
  admin-frontend/src/pages/Home.tsx
  admin-frontend/src/utils/hooks.ts
Labels: feature

#131 修复前端两次点击编辑不能正确显示的问题
  admin-frontend/src/features/subsribeConfigManager/SubscribeModal.tsx
Labels: bug
