Repository MountainDash/nonebot-bison, pull requests merged in 2022-05, with the labels that each got.

#70 修复 #66
  .github/release-drafter.yml
Labels: bug

#72 增加Parse Target功能
  CHANGELOG.md
  src/plugins/nonebot_bison/config_manager.py
  src/plugins/nonebot_bison/platform/bilibili.py
  src/plugins/nonebot_bison/platform/ncm_artist.py
  src/plugins/nonebot_bison/platform/ncm_radio.py
  src/plugins/nonebot_bison/platform/platform.py
  src/plugins/nonebot_bison/platform/weibo.py
  src/plugins/nonebot_bison/plugin_config.py
  tests/platforms/static/bilibili_arknights_profile.json
  tests/platforms/test_bilibili.py
  tests/platforms/test_ncm_artist.py
  tests/platforms/test_ncm_radio.py
  tests/platforms/test_weibo.py
  tests/test_config_manager_abort.py
  tests/test_config_manager_add.py
  tests/utils.py
Labels: feature

#71 增加代理设置
  CHANGELOG.md
  docs/usage/README.md
  src/plugins/nonebot_bison/platform/arknights.py
  src/plugins/nonebot_bison/platform/bilibili.py
  src/plugins/nonebot_bison/platform/ff14.py
  src/plugins/nonebot_bison/platform/ncm_artist.py
  src/plugins/nonebot_bison/platform/ncm_radio.py
  src/plugins/nonebot_bison/platform/rss.py
  src/plugins/nonebot_bison/platform/weibo.py
  src/plugins/nonebot_bison/plugin_config.py
  src/plugins/nonebot_bison/post.py
  src/plugins/nonebot_bison/utils/__init__.py
  src/plugins/nonebot_bison/utils/http.py
  tests/test_proxy.py
Labels: enhancement

#78 添加User-Agent配置
  docs/usage/README.md
  src/plugins/nonebot_bison/plugin_config.py
  src/plugins/nonebot_bison/utils/http.py
  tests/test_proxy.py
Labels: feature

#80 完善开发文档
  docs/dev/README.md
  docs/usage/README.md
Labels: documentation

#82 捕获 JSONDecodeError
  src/plugins/nonebot_bison/platform/platform.py
  src/plugins/nonebot_bison/scheduler.py
Labels: bug
