Repository MountainDash/nonebot-bison, pull requests merged in 2022-11, with the labels that each got.

#139 enable dependabot for update
  .github/dependabot.yml
Labels: skip-changelog

#141 chore: skip pic merge test
  .github/workflows/main.yml
  pyproject.toml
  tests/test_merge_pic.py
Labels: skip-changelog

#140 chore: use pnpm
  admin-frontend/package.json
  admin-frontend/pnpm-lock.yaml
  admin-frontend/src/App.test.tsx
  admin-frontend/yarn.lock
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: skip-changelog

#136 Update nonebot-plugin-htmlrender
  poetry.lock
  pyproject.toml
Labels: dependencies, skip-changelog

#147 :bug: download weibo pics in `parse`
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/platform/weibo.py
  src/plugins/nonebot_bison/utils/http.py
  tests/platforms/test_weibo.py
Labels: bug

#148 :construction_worker: add docker sentry tag for release
  .github/workflows/release.yml
Labels: skip-changelog

#149 :white_check_mark: add pic merge test back
  .github/workflows/main.yml
  tests/test_merge_pic.py
Labels: skip-changelog

#151 fix(bilibili-live): 修正一些错误的api
  src/plugins/nonebot_bison/platform/bilibili.py
  tests/platforms/test_bilibili_bangumi.py
  tests/platforms/test_bilibili_live.py
Labels: bug

#154 修复后台无法删除 RSS 订阅的问题
  admin-frontend/src/features/subsribeConfigManager/subscribeConfigSlice.ts
Labels: bug

#157 在微博订阅账号为空时，不抛出错误
  src/plugins/nonebot_bison/platform/weibo.py
Labels: bug, skip-changelog

#133 适配 python3.11
  .github/actions/setup-python/action.yml
  .github/workflows/main.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: enhancement
