Repository MountainDash/nonebot-bison, pull requests merged in 2023-02, with the labels that each got.

#181 refactor: 清理代码和依赖，并调整目录结构
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/config/db_model.py
  src/plugins/nonebot_bison/config/migrate/README
  src/plugins/nonebot_bison/config/migrate/__init__.py
  src/plugins/nonebot_bison/config/migrate/env.py
  src/plugins/nonebot_bison/config/migrate/script.py.mako
  src/plugins/nonebot_bison/config/migrations/0571870f5222_init_db.py
  src/plugins/nonebot_bison/config/migrations/4a46ba54a3f3_alter_type.py
  src/plugins/nonebot_bison/config/migrations/5da28f6facb3_rename_tables.py
  src/plugins/nonebot_bison/config/migrations/5f3370328e44_add_time_weight_table.py
  src/plugins/nonebot_bison/config/migrations/a333d6224193_add_last_scheduled_time.py
  src/plugins/nonebot_bison/config/migrations/c97c445e2bdb_add_constraint.py
  src/plugins/nonebot_bison/scheduler/old_sched.py
Labels: skip-changelog

#176 feat(workflow pytest): 添加打上test-render的标签后进行带render标记测试的功能
  .github/workflows/main.yml
  codecov.yml
  tests/test_render.py
Labels: all-test

#184 适配 Nonebot 插件元数据
  src/plugins/nonebot_bison/__init__.py
Labels: feature

#182 :bookmark: release 0.7.0
  pyproject.toml
  src/plugins/nonebot_bison/__init__.py
Labels: major, skip-changelog, all-test

#185 解决使用队列发送时产生大量日志的问题
  src/plugins/nonebot_bison/scheduler/aps.py
  src/plugins/nonebot_bison/send.py
  tests/test_send.py
Labels: enhancement

#189 在 docker image 中添加 fastapi
  docker/Dockerfile_with_frontend
  docker/Dockerfile_with_frontend_sentry
Labels: skip-changelog

#192 修复依赖项不足的问题
  docker/Dockerfile_with_frontend
  docker/Dockerfile_with_frontend_sentry
Labels: skip-changelog

#198 调整群内订阅命令回复文本的位置，为`后台管理`命令添加别名`管理后台`
  src/plugins/nonebot_bison/admin_page/__init__.py
  src/plugins/nonebot_bison/config_manager.py
  tests/utils.py
Labels: enhancement

#200 修复使用 PostgreSQL 时迁移脚本的报错
  src/plugins/nonebot_bison/config/migrations/4a46ba54a3f3_alter_type.py
Labels: bug

#204 :arrow_up: upgrade aiofiles
  poetry.lock
  pyproject.toml
Labels: dependencies
