Repository MountainDash/nonebot-bison, pull requests merged in 2023-07, with the labels that each got.

#276 update dependencies
  .github/workflows/main.yml
Labels: dependencies

#288 :arrow_up: upgrade vuepress
  package.json
  pnpm-lock.yaml
Labels: dependencies

#305 适配明日方舟新版公告栏API
  nonebot_bison/platform/arknights.py
  nonebot_bison/post/templates/ark_announce/index.html
  nonebot_bison/post/templates/ark_announce/style.css
  tests/platforms/static/arknights-detail-805
  tests/platforms/static/arknights-detail-807
  tests/platforms/static/arknights_list_-1.json
  tests/platforms/static/arknights_list_0.json
  tests/platforms/static/arknights_list_1.json
  tests/platforms/test_arknights.py
Labels: feature

#303 修复RSS推送时没有URL消息的bug
  nonebot_bison/post/plain_post.py
  tests/post/test_plain_post.py
Labels: bug
