Repository MountainDash/nonebot-bison, pull requests merged in 2023-03, with the labels that each got.

#209 :recycle: 直接使用官方定时任务插件
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/__init__.py
  src/plugins/nonebot_bison/bootstrap.py
  src/plugins/nonebot_bison/scheduler/aps.py
  src/plugins/nonebot_bison/scheduler/scheduler.py
Labels: skip-changelog

#207 ✅ 升级至 NoneBug 0.3
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/platform/mcbbsnews.py
  tests/config/test_config_legacy.py
  tests/config/test_scheduler_conf.py
  tests/conftest.py
  tests/platforms/test_weibo.py
  tests/scheduler/test_scheduler.py
  tests/test_config_manager_add.py
  tests/test_get_bot.py
  tests/test_proxy.py
  tests/test_send.py
  tests/utils.py
Labels: dependencies, all-test

#186 :construction_worker: use pytest-xdist to accelerate test
  .github/workflows/main.yml
  poetry.lock
  pyproject.toml
  tests/platforms/static/mcbbsnews/mcbbsnews_raw_post_list.json
  tests/platforms/static/mcbbsnews/mock/mcbbsnews_bedrock_express.html
  tests/platforms/static/mcbbsnews/mock/mcbbsnews_bedrocknews.html
  tests/platforms/static/mcbbsnews/mock/mcbbsnews_java_express.html
  tests/platforms/static/mcbbsnews/mock/mcbbsnews_javanews.html
  tests/platforms/static/mcbbsnews/mock/mcbbsnews_merch.html
  tests/platforms/test_mcbbsnews.py
Labels: skip-changelog, all-test

#212 :art: 调整旧版数据库加载逻辑
  nonebot_bison/config/config_legacy.py
  nonebot_bison/config/db.py
  tests/config/test_config_legacy.py
  tests/config/test_data_migration.py
  tests/conftest.py
Labels: skip-changelog

#214 :zap: improve export performace
  nonebot_bison/config/subs_io/subs_io.py
  nonebot_bison/script/cli.py
  tests/subs_io/test_subs_io.py
Labels: skip-changelog

#215 :bug: register db hook after init scheduler
  nonebot_bison/config/db_config.py
  nonebot_bison/scheduler/manager.py
Labels: skip-changelog

#218 :bookmark: release 0.7.1
  nonebot_bison/__init__.py
  pyproject.toml
Labels: skip-changelog, all-test

#221 在未安装 fastapi 时不加载 webui
  nonebot_bison/admin_page/__init__.py
Labels: bug

#222 调整 scheduler log level
  nonebot_bison/scheduler/scheduler.py
Labels: enhancement

#223 调整 bilibili 网络报错
  nonebot_bison/platform/bilibili.py
Labels: feature

#226 :children_crossing: add issue template
  .github/ISSUE_TEMPLATE/问题报告.md
Labels: skip-changelog

#227 可以关闭日志中的网络报错
  docs/usage/README.md
  nonebot_bison/platform/platform.py
  nonebot_bison/plugin_config.py
Labels: feature
