Repository MountainDash/nonebot-bison, pull requests merged in 2023-08, with the labels that each got.

#323 :arrow_up: 放宽 datastore 的依赖限制
  poetry.lock
  pyproject.toml
Labels: dependencies

#331 :wrench: 降低前端dependabot检查频率
  .github/dependabot.yml
Labels: skip-changelog

#349 适配 SAA 0.3
  nonebot_bison/config/migrations/f9baef347cc8_remove_old_target.py
  poetry.lock
  pyproject.toml
Labels: bug

#353 Docs: 更新 README 样式
  README.md
Labels: skip-changelog

#290 提供批量 api 接口
  nonebot_bison/platform/bilibili.py
  nonebot_bison/platform/platform.py
  nonebot_bison/scheduler/manager.py
  nonebot_bison/scheduler/scheduler.py
  nonebot_bison/types.py
  tests/platforms/test_arknights.py
  tests/platforms/test_bilibili.py
  tests/platforms/test_bilibili_bangumi.py
  tests/platforms/test_bilibili_live.py
  tests/platforms/test_ff14.py
  tests/platforms/test_ncm_artist.py
  tests/platforms/test_ncm_radio.py
  tests/platforms/test_platform.py
  tests/platforms/test_rss.py
  tests/platforms/test_weibo.py
  tests/scheduler/test_scheduler.py
Labels: feature
