Repository MountainDash/nonebot-bison, pull requests merged in 2023-01, with the labels that each got.

#177 :construction_worker: change poetry install action
  .github/actions/setup-python/action.yml
  .github/workflows/main.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: skip-changelog

#178 feat: 适配最新的 DataStore 插件，并切换模型为 SQLModel
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/bootstrap.py
  src/plugins/nonebot_bison/config/__init__.py
  src/plugins/nonebot_bison/config/db.py
  src/plugins/nonebot_bison/config/db_config.py
  src/plugins/nonebot_bison/config/db_model.py
  src/plugins/nonebot_bison/config/migrate/versions/5da28f6facb3_rename_tables.py
  tests/config/test_config_operation.py
  tests/config/test_data_migration.py
  tests/conftest.py
Labels: Breaking

#180 ci: 升级 pre-commit hooks 版本，解决报错问题
  .pre-commit-config.yaml
Labels: dependencies

#179 支持连接多个机器人
  poetry.lock
  pyproject.toml
  src/plugins/nonebot_bison/admin_page/api.py
  src/plugins/nonebot_bison/scheduler/scheduler.py
  src/plugins/nonebot_bison/send.py
  src/plugins/nonebot_bison/utils/get_bot.py
  tests/test_get_bot.py
Labels: feature
