Repository MountainDash/nonebot-bison, pull requests merged in 2024-06, with the labels that each got.

#552 修复前端开发部分文档的问题
  docs/dev/README.md
Labels: documentation

#559 :bug: remove unneeded default client
  nonebot_bison/utils/site.py
Labels: skip-changelog

#525 B站蹲饼修复
  nonebot_bison/platform/bilibili/__init__.py
  nonebot_bison/platform/bilibili/models.py
  nonebot_bison/platform/bilibili/platforms.py
  nonebot_bison/platform/bilibili/scheduler.py
  nonebot_bison/utils/__init__.py
  poetry.lock
  pyproject.toml
  tests/platforms/static/bilibili-dynamic-live-rcmd.json
  tests/platforms/static/bilibili-new.json
  tests/platforms/static/bilibili_bing_list.json
  tests/platforms/static/bilibili_strange_post-0.json
  tests/platforms/static/bilibili_strange_post.json
  tests/platforms/test_bilibili.py
  tests/platforms/test_bilibili_live.py
  tests/scheduler/test_site.py
Labels: bug

#558 :construction_worker: 删除dependabot更新检查
  .github/dependabot.yml
Labels: skip-changelog

#579 🔧 更新 renovatebot 配置
  renovate.json
Labels: skip-changelog
