Repository MountainDash/nonebot-bison, pull requests merged in 2024-10, with the labels that each got.

#634 :construction_worker: 将自动化工具中的 yarn 替换为 pnpm
  .devcontainer/devcontainer.json
  .github/actions/build-docs/action.yml
  .github/actions/build-frontend/action.yml
  .github/actions/setup-node/action.yml
  docker/Dockerfile
Labels: skip-changelog

#630 ✨ feat(ISSUE_TEMPLATE): 修改问题报告模板
  .github/ISSUE_TEMPLATE/issue.yml
  .github/ISSUE_TEMPLATE/问题报告.md
Labels: skip-changelog

#643 :sparkles: 更新默认UA为Windows平台
  docker.env.prod
  nonebot_bison/plugin_config.py
  tests/test_context.py
Labels: enhancement

#644 :bug: 修复B站获取匿名Cookie逻辑
  nonebot_bison/platform/bilibili/scheduler.py
Labels: bug

#645 🐛 修复微博更换长内容接口
  nonebot_bison/platform/weibo.py
  tests/platforms/static/weibo_detail_4645748019299849
  tests/platforms/static/weibo_detail_4649031014551911
  tests/platforms/test_weibo.py
Labels: bug
