Repository MountainDash/nonebot-bison, pull requests merged in 2024-03, with the labels that each got.

#486 修复后台管理界面无法获取群信息的问题
  nonebot_bison/admin_page/types.py
Labels: bug

#485 更新文档以适配 pyd2 的用法
  docker-compose.yml
  docs/usage/install.md
Labels: documentation

#497 💚 修复 pre-commit 检查
  .pre-commit-config.yaml
Labels: skip-changelog

#495 Arknights 公告分类 过滤不可访问的 URL
  nonebot_bison/platform/arknights.py
  poetry.lock
  tests/platforms/test_arknights.py
Labels: bug

#496 使用 yarl.URL 拼接 outer_url
  nonebot_bison/admin_page/__init__.py
  nonebot_bison/plugin_config.py
  poetry.lock
  pyproject.toml
  tests/test_admin_page.py
Labels: enhancement

#473 独立 bilibili-live 的 SchedConf
  nonebot_bison/platform/bilibili.py
  tests/platforms/test_bilibili_live.py
  tests/scheduler/test_scheduler.py
Labels: enhancement

#504 更详细的微博
  nonebot_bison/platform/weibo.py
  poetry.lock
  pyproject.toml
  tests/platforms/static/weibo_detail_4645748019299849
  tests/platforms/static/weibo_detail_4649031014551911
  tests/platforms/test_weibo.py
Labels: enhancement

#514 :memo: 清理CHANGELOG.md
  CHANGELOG.md
Labels: skip-changelog
