Repository MountainDash/nonebot-bison, pull requests merged in 2025-01, with the labels that each got.

#673 :recycle: 将 user_cookie 重命名为 identified_cookie
  docs/dev/cookie.md
  nonebot_bison/admin_page/api.py
  nonebot_bison/sub_manager/add_cookie.py
  nonebot_bison/sub_manager/add_cookie_target.py
  nonebot_bison/utils/site.py
  tests/config/test_cookie.py
Labels: skip-changelog

#631 B站直播无法获取关键帧时使用封面
  nonebot_bison/platform/bilibili/platforms.py
  tests/platforms/test_bilibili_live.py
Labels: bug

#664 优化 B站 Cookie 选择策略
  nonebot_bison/platform/bilibili/scheduler.py
  nonebot_bison/utils/site.py
Labels: enhancement
